import { Card, CardContent } from "@/components/ui/card";
import { Edit, Target, Zap, Copy } from "lucide-react";

const steps = [
  {
    number: 1,
    icon: Edit,
    title: "Input Your Idea into Our Platform",
    description: "Type your basic question or describe your goal to our system. No special formatting is needed for this initial step of prompt generation.",
    image: "📝"
  },
  {
    number: 2,
    icon: Target,
    title: "Select Target AI Model (Recommended)",
    description: "Choose the AI model (e.g., ChatGPT, Midjourney) for which our system should tailor the prompt for optimal performance.",
    image: "🎯"
  },
  {
    number: 3,
    icon: Zap,
    title: "AutoPrompt Creates Optimized Prompts",
    description: "Our AI engine instantly analyzes and transforms your input into an optimized, professional prompt, structured for your chosen model. This is a key function of our prompt generator.",
    image: "⚡"
  },
  {
    number: 4,
    icon: Copy,
    title: "Copy Your Enhanced Prompt",
    description: "With one click, copy the high-quality prompt generated by our tool and use it in your AI application for significantly improved results from the AI.",
    image: "📋"
  }
];

export const HowItWorks = () => {
  return (
    <section className="py-16">
      <div className="max-w-7xl mx-auto px-6">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-4 text-foreground">
            How the AutoPrompt Automatic Prompt Generator Tool Works
          </h2>
          <p className="text-lg text-muted-foreground max-w-4xl mx-auto">
            Generate expertly optimized prompts with our AI-powered platform in a few simple steps. Using AutoPrompt is straightforward:
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8">
          {steps.map((step, index) => (
            <Card key={index} className="relative overflow-hidden border-0 shadow-card hover:shadow-hero transition-shadow duration-300">
              <CardContent className="p-8">
                <div className="flex items-start gap-6">
                  <div className="flex-shrink-0">
                    <div className="w-16 h-16 bg-brand-red rounded-full flex items-center justify-center text-white font-bold text-xl">
                      {step.number}
                    </div>
                  </div>
                  
                  <div className="flex-1">
                    <h3 className="text-xl font-semibold mb-3 text-foreground">
                      {step.number}. {step.title}
                    </h3>
                    <p className="text-muted-foreground mb-6">
                      {step.description}
                    </p>
                    
                    <div className="h-32 bg-gradient-card rounded-lg flex items-center justify-center">
                      <div className="text-4xl">{step.image}</div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Additional illustration */}
        <div className="mt-16 text-center">
          <div className="max-w-2xl mx-auto bg-gradient-card rounded-2xl p-8 shadow-card">
            <div className="h-32 flex items-center justify-center text-6xl text-brand-red/30 mb-4">
              🚀
            </div>
            <h3 className="text-xl font-semibold text-foreground mb-2">
              Ready to Transform Your AI Interactions?
            </h3>
            <p className="text-muted-foreground">
              Start generating professional prompts in seconds with AutoPrompt's intelligent AI system.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};